# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 3
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run tests
        run: mvn compile test
        env:
          TWILIO_ACCOUNT_SID: YOUR-TWILIO-ACCOUNT-SID
          TWILIO_AUTH_TOKEN: YOUR-TWILIO-AUTH-TOKEN
          TWILIO_PHONE_NUMBER: YOUR-TWILIO-PHONE-NUMBER
